### ISSUE TITLE
Vignette has lost its illustrations

### ISSUE THREAD

**Issue by larspett** [rekonstrukt/swedishbutterflies#8]
The illustrations that used to be in the vignette are not drawn after the lastest update

**Comment by mskyttner** [comment]
Here is the one that gets generated from devtools::build_vignettes for v0.1.2: 

https://rawgit.com/rekonstrukt/swedishbutterflies/master/inst/doc/sebms-intro.html

I just tested this in a VirtualBox with Windows 8 now, and it seems to work there, the vignette has the plots in it. But I have no easy way to test it with OSX... Are no plots/images generated in the vignette when you build it locally? I think I need more details to replicate this issue.

**Comment by larspett** [comment]
Most likely myself being a n00b on Giothub, I got the impression that Github would render Rmds on the fly at the site but now that I have looked around it seems that is not the case (?). Your devtool build generates the correct vignette
